=== yamunaacharya/html-lists/schema/lab12.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="bank">
<xs:complexType>
<xs:sequence>
   <xs:element name="customer" maxOccurs="unbounded">
   <xs:complexType>
   <xs:sequence>
      <xs:element name="customerId" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
   </xs:sequence>
   </xs:complexType>
   </xs:element>

    
   <xs:element name="accounts" maxOccurs="unbounded">
   <xs:complexType>
   <xs:sequence>
      <xs:element name="accountId" type="xs:string"/>
      <xs:element name="branchId" type="xs:string"/>
      <xs:element name="customerId" type="xs:string"/>
      <xs:element name="accountType" type="xs:string"/>
      <xs:element name="balance" type="xs:string"/>
   </xs:sequence>
   </xs:complexType>
   </xs:element>

   <xs:element name="employee" maxOccurs="unbounded">
   <xs:complexType>
   <xs:sequence>
      <xs:element name="employeeId" type="xs:string"/>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="designation" type="xs:string"/>
      <xs:element name="DOJ" type="xs:string"/>
      <xs:element name="salary" type="xs:string"/>
      <xs:element name="address" type="xs:string"/>
      </xs:sequence>
      </xs:complexType>
      </xs:element>

</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== yamunaacharya/html-lists/schema/lab12.xml
<?xml version="1.0" encoding="UTF-8"?>
<bank xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="lab12.xsd">

    <customer>
      <customerId></customerId>
      <name></name>
      <address></address>
    </customer>

    <accounts>
       <accountId></accountId>
       <branchId></branchId>
       <customerId></customerId>
       <accountType></accountType>
       <balance></balance>
    </accounts>

    <employee>
        <employeeId></employeeId>
        <name></name>
        <designation></designation>
        <DOJ></DOJ>
        <salary></salary>
        <address></address>
    
    </employee>

</bank>
